name: Include What You Use
on: [push]
jobs:
  iwyu:
    runs-on: ubuntu-latest
    steps:
      - name: Run Include What You Use
        uses: EmilGedda/include-what-you-use-action@v1
        with:
          compilation-database-path: "."
          output-format: "iwyu" # Or 'clang'
          no-error: "false"
